name: Build Tauri App for Linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Linux build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libsoup-3.0-dev \
            libjavascriptcoregtk-4.1-dev \
            build-essential \
            pkg-config \
            curl

      - name: Debug pkg-config
        run: |
          pkg-config --list-all | grep webkit
          ls -la /usr/lib/pkgconfig | grep webkit

      - name: Build Tauri app
        run: |
          export WEBKIT2GTK_VERSION=4.0
          npm install
          npm run tauri build

      - name: Install Node dependencies
        run: npm install

      - name: Build Tauri app
        run: |
            export WEBKIT2GTK_WEBKIT2GTK_4_VERSION=4.0
            npm run tauri build


      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: src-tauri/target/release/bundle

