name: Build Tauri App for Linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Enable Universe & Update
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt-get update

      - name: Install Linux build dependencies
        run: |
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            build-essential \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            squashfs-tools \
            curl

      - name: Install Node dependencies
        run: npm install

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: src-tauri/target/release/bundle

