name: Build Tauri App for Linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Linux system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            squashfs-tools

      - name: Install NPM dependencies
        run: npm install

      - name: Build Tauri app for Linux
        run: npm run tauri build

      - name: Upload Linux build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-tauri-build
          path: src-tauri/target/release/bundle/
